name: Test setup script
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test setup script
    runs-on: windows-latest
    strategy:
      matrix:
        arguments: ["", "-InstallPython"]
    steps:
      - name: Install Visual Studio Code
        shell: powershell
        run: |
          Import-Module BitsTransfer
          $VSCodePath = "$Env:TEMP/VSCodeUserSetup-x64.exe"
          Start-BitsTransfer "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64" "$Env:TEMP/VSCodeUserSetup-x64.exe"
          Start-Process $VSCodePath -ArgumentList "/verysilent", "/mergetasks=addtopath,!runcode"

      - name: Run setup-environment.ps1
        shell: powershell
        run: |
          echo $Env:PATH
#          . { Set-ExecutionPolicy Bypass -Scope Process -Force } *> $null; . ([scriptblock]::Create((irm 'https://raw.githubusercontent.com/mon-jai/environment-setup/main/setup-environment.ps1')))`
#            ${{ matrix.arguments }}
#          Write-Host $Error
