name: Test setup script
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test setup script
    runs-on: windows-latest
    strategy:
#      matrix:
#        arguments: ["", "-InstallPython"]
    steps:
      - name: Install Visual Studio Code
        shell: powershell
        run: |
          choco install vscode

      - name: Run setup-environment.ps1
        shell: powershell
        run: |
         choco list -lo
 #         echo $Env:PATH
 #         . { Set-ExecutionPolicy Bypass -Scope Process -Force } *> $null; . ([scriptblock]::Create((irm 'https://raw.githubusercontent.com/mon-jai/environment-setup/main/setup-environment.ps1')))`
 #           ${{ matrix.arguments }}
#          Write-Host $Error
