name: Test setup script
on: [push, workflow_dispatch]

jobs:
  test:
    name: Test setup script
    runs-on: windows-latest
    concurrency:
      group: ${{ toJSON( matrix.arguments ) }}
      cancel-in-progress: true
    strategy:
      matrix:
        arguments: ["", "-lang python", "-lang c++", "-lang cpp"]
    steps:
      - name: Download Visual Studio Code
        shell: powershell
        run: |
          Import-Module BitsTransfer

          $VSCodeDownloadPath = "$Env:TEMP\vscode.zip"
          $VSCodePath = "$Env:UserProfile\vscode"

          Start-BitsTransfer "https://code.visualstudio.com/sha/download?build=stable&os=win32-x64-archive" $VSCodeDownloadPath
          Expand-Archive $VSCodeDownloadPath -DestinationPath $VSCodePath

          "$VSCodePath\bin\" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Run setup-environment.ps1
        shell: powershell
        run: |
          . { Set-ExecutionPolicy Bypass -Scope Process -Force } *> $null; . ([scriptblock]::Create((irm 'https://raw.githubusercontent.com/mon-jai/environment-setup/${{ github.sha }}/setup-environment.ps1')))`
            ${{ matrix.arguments }}
          # https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples
          "SetupLogFilePath=$Env:SetupLogFilePath" >> $Env:GITHUB_ENV

      - name: Show generated VS Code settings
        run: |
          Get-Content -Path "$Env:APPDATA\Code\User\settings.json"

      - name: Show setup logs
        run: |
          Get-Content -Path ${{ env.SetupLogFilePath }}
